name: Rust-wasm-deploy


on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: wasm-pack-action
      uses: jetli/wasm-pack-action@v0.3.0
      #with:
        # Optional version of wasm-pack to install (eg. "v0.9.1", "latest")
        #version: # optional, default is latest
    - name: Build
      run: wasm-pack build --target web
    - name: WASM Github Pages Generate
      uses: acblog/wasm-ghpages-generate-action@v0.0.2
      with:
        # Folder path in domain, ends with '/', default to '/'.
        #domain: # optional, default is /
        # Segment count in domain, default to '0'.
        #segmentCount: # optional, default is 0
        # App directory with settings files, not endswith '/', default to './app'.
        app: ./ # optional, default is ./app
        # Dist directory, not endswith '/', default to './dist'.
        #dist: # optional, default is ./dist
